
#ifndef _REG_TIM8_H_
#define _REG_TIM8_H_

#include "Std_Types.h"
#include "reg_functions.h"

#define TIM8_CR1                        REGISTER(0x40013400UL)
#define TIM8_CR1_CEN_POS                0UL
#define TIM8_CR1_CEN_LEN                1UL
#define TIM8_CR1_UDIS_POS               1UL
#define TIM8_CR1_UDIS_LEN               1UL
#define TIM8_CR1_URS_POS                2UL
#define TIM8_CR1_URS_LEN                1UL
#define TIM8_CR1_OPM_POS                3UL
#define TIM8_CR1_OPM_LEN                1UL
#define TIM8_CR1_DIR_POS                4UL
#define TIM8_CR1_DIR_LEN                1UL
#define TIM8_CR1_CMS_POS                5UL
#define TIM8_CR1_CMS_LEN                2UL
#define TIM8_CR1_ARPE_POS               7UL
#define TIM8_CR1_ARPE_LEN               1UL
#define TIM8_CR1_CKD_POS                8UL
#define TIM8_CR1_CKD_LEN                2UL
#define TIM8_CR1_UIFREMAP_POS           11UL
#define TIM8_CR1_UIFREMAP_LEN           1UL

#define TIM8_CR2                        REGISTER(0x40013404UL)
#define TIM8_CR2_CCPC_POS               0UL
#define TIM8_CR2_CCPC_LEN               1UL
#define TIM8_CR2_CCUS_POS               2UL
#define TIM8_CR2_CCUS_LEN               1UL
#define TIM8_CR2_CCDS_POS               3UL
#define TIM8_CR2_CCDS_LEN               1UL
#define TIM8_CR2_MMS_POS                4UL
#define TIM8_CR2_MMS_LEN                3UL
#define TIM8_CR2_TI1S_POS               7UL
#define TIM8_CR2_TI1S_LEN               1UL
#define TIM8_CR2_OIS1_POS               8UL
#define TIM8_CR2_OIS1_LEN               1UL
#define TIM8_CR2_OIS1N_POS              9UL
#define TIM8_CR2_OIS1N_LEN              1UL
#define TIM8_CR2_OIS2_POS               10UL
#define TIM8_CR2_OIS2_LEN               1UL
#define TIM8_CR2_OIS2N_POS              11UL
#define TIM8_CR2_OIS2N_LEN              1UL
#define TIM8_CR2_OIS3_POS               12UL
#define TIM8_CR2_OIS3_LEN               1UL
#define TIM8_CR2_OIS3N_POS              13UL
#define TIM8_CR2_OIS3N_LEN              1UL
#define TIM8_CR2_OIS4_POS               14UL
#define TIM8_CR2_OIS4_LEN               1UL
#define TIM8_CR2_OIS5_POS               16UL
#define TIM8_CR2_OIS5_LEN               1UL
#define TIM8_CR2_OIS6_POS               18UL
#define TIM8_CR2_OIS6_LEN               1UL
#define TIM8_CR2_MMS2_POS               20UL
#define TIM8_CR2_MMS2_LEN               4UL

#define TIM8_SMCR                       REGISTER(0x40013408UL)
#define TIM8_SMCR_SMS_POS               0UL
#define TIM8_SMCR_SMS_LEN               3UL
#define TIM8_SMCR_OCCS_POS              3UL
#define TIM8_SMCR_OCCS_LEN              1UL
#define TIM8_SMCR_TS_POS                4UL
#define TIM8_SMCR_TS_LEN                3UL
#define TIM8_SMCR_MSM_POS               7UL
#define TIM8_SMCR_MSM_LEN               1UL
#define TIM8_SMCR_ETF_POS               8UL
#define TIM8_SMCR_ETF_LEN               4UL
#define TIM8_SMCR_ETPS_POS              12UL
#define TIM8_SMCR_ETPS_LEN              2UL
#define TIM8_SMCR_ECE_POS               14UL
#define TIM8_SMCR_ECE_LEN               1UL
#define TIM8_SMCR_ETP_POS               15UL
#define TIM8_SMCR_ETP_LEN               1UL
#define TIM8_SMCR_SMS3_POS              16UL
#define TIM8_SMCR_SMS3_LEN              1UL

#define TIM8_DIER                       REGISTER(0x4001340CUL)
#define TIM8_DIER_UIE_POS               0UL
#define TIM8_DIER_UIE_LEN               1UL
#define TIM8_DIER_CC1IE_POS             1UL
#define TIM8_DIER_CC1IE_LEN             1UL
#define TIM8_DIER_CC2IE_POS             2UL
#define TIM8_DIER_CC2IE_LEN             1UL
#define TIM8_DIER_CC3IE_POS             3UL
#define TIM8_DIER_CC3IE_LEN             1UL
#define TIM8_DIER_CC4IE_POS             4UL
#define TIM8_DIER_CC4IE_LEN             1UL
#define TIM8_DIER_COMIE_POS             5UL
#define TIM8_DIER_COMIE_LEN             1UL
#define TIM8_DIER_TIE_POS               6UL
#define TIM8_DIER_TIE_LEN               1UL
#define TIM8_DIER_BIE_POS               7UL
#define TIM8_DIER_BIE_LEN               1UL
#define TIM8_DIER_UDE_POS               8UL
#define TIM8_DIER_UDE_LEN               1UL
#define TIM8_DIER_CC1DE_POS             9UL
#define TIM8_DIER_CC1DE_LEN             1UL
#define TIM8_DIER_CC2DE_POS             10UL
#define TIM8_DIER_CC2DE_LEN             1UL
#define TIM8_DIER_CC3DE_POS             11UL
#define TIM8_DIER_CC3DE_LEN             1UL
#define TIM8_DIER_CC4DE_POS             12UL
#define TIM8_DIER_CC4DE_LEN             1UL
#define TIM8_DIER_COMDE_POS             13UL
#define TIM8_DIER_COMDE_LEN             1UL
#define TIM8_DIER_TDE_POS               14UL
#define TIM8_DIER_TDE_LEN               1UL

#define TIM8_SR                         REGISTER(0x40013410UL)
#define TIM8_SR_UIF_POS                 0UL
#define TIM8_SR_UIF_LEN                 1UL
#define TIM8_SR_CC1IF_POS               1UL
#define TIM8_SR_CC1IF_LEN               1UL
#define TIM8_SR_CC2IF_POS               2UL
#define TIM8_SR_CC2IF_LEN               1UL
#define TIM8_SR_CC3IF_POS               3UL
#define TIM8_SR_CC3IF_LEN               1UL
#define TIM8_SR_CC4IF_POS               4UL
#define TIM8_SR_CC4IF_LEN               1UL
#define TIM8_SR_COMIF_POS               5UL
#define TIM8_SR_COMIF_LEN               1UL
#define TIM8_SR_TIF_POS                 6UL
#define TIM8_SR_TIF_LEN                 1UL
#define TIM8_SR_BIF_POS                 7UL
#define TIM8_SR_BIF_LEN                 1UL
#define TIM8_SR_B2IF_POS                8UL
#define TIM8_SR_B2IF_LEN                1UL
#define TIM8_SR_CC1OF_POS               9UL
#define TIM8_SR_CC1OF_LEN               1UL
#define TIM8_SR_CC2OF_POS               10UL
#define TIM8_SR_CC2OF_LEN               1UL
#define TIM8_SR_CC3OF_POS               11UL
#define TIM8_SR_CC3OF_LEN               1UL
#define TIM8_SR_CC4OF_POS               12UL
#define TIM8_SR_CC4OF_LEN               1UL
#define TIM8_SR_SBIF_POS                13UL
#define TIM8_SR_SBIF_LEN                1UL
#define TIM8_SR_CC5IF_POS               16UL
#define TIM8_SR_CC5IF_LEN               1UL
#define TIM8_SR_CC6IF_POS               17UL
#define TIM8_SR_CC6IF_LEN               1UL

#define TIM8_EGR                        REGISTER(0x40013414UL)
#define TIM8_EGR_UG_POS                 0UL
#define TIM8_EGR_UG_LEN                 1UL
#define TIM8_EGR_CC1G_POS               1UL
#define TIM8_EGR_CC1G_LEN               1UL
#define TIM8_EGR_CC2G_POS               2UL
#define TIM8_EGR_CC2G_LEN               1UL
#define TIM8_EGR_CC3G_POS               3UL
#define TIM8_EGR_CC3G_LEN               1UL
#define TIM8_EGR_CC4G_POS               4UL
#define TIM8_EGR_CC4G_LEN               1UL
#define TIM8_EGR_COMG_POS               5UL
#define TIM8_EGR_COMG_LEN               1UL
#define TIM8_EGR_TG_POS                 6UL
#define TIM8_EGR_TG_LEN                 1UL
#define TIM8_EGR_BG_POS                 7UL
#define TIM8_EGR_BG_LEN                 1UL
#define TIM8_EGR_B2G_POS                8UL
#define TIM8_EGR_B2G_LEN                1UL

#define TIM8_CCMR1                      REGISTER(0x40013418UL)
#define TIM8_CCMR1_CC1S_POS             0UL
#define TIM8_CCMR1_CC1S_LEN             2UL
#define TIM8_CCMR1_OC1FE_POS            2UL
#define TIM8_CCMR1_OC1FE_LEN            1UL
#define TIM8_CCMR1_OC1PE_POS            3UL
#define TIM8_CCMR1_OC1PE_LEN            1UL
#define TIM8_CCMR1_OC1M_POS             4UL
#define TIM8_CCMR1_OC1M_LEN             3UL
#define TIM8_CCMR1_OC1CE_POS            7UL
#define TIM8_CCMR1_OC1CE_LEN            1UL
#define TIM8_CCMR1_CC2S_POS             8UL
#define TIM8_CCMR1_CC2S_LEN             2UL
#define TIM8_CCMR1_OC2FE_POS            10UL
#define TIM8_CCMR1_OC2FE_LEN            1UL
#define TIM8_CCMR1_OC2PE_POS            11UL
#define TIM8_CCMR1_OC2PE_LEN            1UL
#define TIM8_CCMR1_OC2M_POS             12UL
#define TIM8_CCMR1_OC2M_LEN             3UL
#define TIM8_CCMR1_OC2CE_POS            15UL
#define TIM8_CCMR1_OC2CE_LEN            1UL
#define TIM8_CCMR1_OC1M3_POS            16UL
#define TIM8_CCMR1_OC1M3_LEN            1UL
#define TIM8_CCMR1_OC2M3_POS            24UL
#define TIM8_CCMR1_OC2M3_LEN            1UL
#define TIM8_CCMR1_IC1PSC_POS           2UL
#define TIM8_CCMR1_IC1PSC_LEN           2UL
#define TIM8_CCMR1_IC1F_POS             4UL
#define TIM8_CCMR1_IC1F_LEN             4UL
#define TIM8_CCMR1_IC2PSC_POS           10UL
#define TIM8_CCMR1_IC2PSC_LEN           2UL
#define TIM8_CCMR1_IC2F_POS             12UL
#define TIM8_CCMR1_IC2F_LEN             4UL

#define TIM8_CCMR2                      REGISTER(0x4001341CUL)
#define TIM8_CCMR2_CC3S_POS             0UL
#define TIM8_CCMR2_CC3S_LEN             2UL
#define TIM8_CCMR2_OC3FE_POS            2UL
#define TIM8_CCMR2_OC3FE_LEN            1UL
#define TIM8_CCMR2_OC3PE_POS            3UL
#define TIM8_CCMR2_OC3PE_LEN            1UL
#define TIM8_CCMR2_OC3M_POS             4UL
#define TIM8_CCMR2_OC3M_LEN             3UL
#define TIM8_CCMR2_OC3CE_POS            7UL
#define TIM8_CCMR2_OC3CE_LEN            1UL
#define TIM8_CCMR2_CC4S_POS             8UL
#define TIM8_CCMR2_CC4S_LEN             2UL
#define TIM8_CCMR2_OC4FE_POS            10UL
#define TIM8_CCMR2_OC4FE_LEN            1UL
#define TIM8_CCMR2_OC4PE_POS            11UL
#define TIM8_CCMR2_OC4PE_LEN            1UL
#define TIM8_CCMR2_OC4M_POS             12UL
#define TIM8_CCMR2_OC4M_LEN             3UL
#define TIM8_CCMR2_OC4CE_POS            15UL
#define TIM8_CCMR2_OC4CE_LEN            1UL
#define TIM8_CCMR2_OC3M3_POS            16UL
#define TIM8_CCMR2_OC3M3_LEN            1UL
#define TIM8_CCMR2_OC4M3_POS            24UL
#define TIM8_CCMR2_OC4M3_LEN            1UL
#define TIM8_CCMR2_IC3PSC_POS           2UL
#define TIM8_CCMR2_IC3PSC_LEN           2UL
#define TIM8_CCMR2_IC3F_POS             4UL
#define TIM8_CCMR2_IC3F_LEN             4UL
#define TIM8_CCMR2_IC4PSC_POS           10UL
#define TIM8_CCMR2_IC4PSC_LEN           2UL
#define TIM8_CCMR2_IC4F_POS             12UL
#define TIM8_CCMR2_IC4F_LEN             4UL

#define TIM8_CCER                       REGISTER(0x40013420UL)
#define TIM8_CCER_CC1E_POS              0UL
#define TIM8_CCER_CC1E_LEN              1UL
#define TIM8_CCER_CC1P_POS              1UL
#define TIM8_CCER_CC1P_LEN              1UL
#define TIM8_CCER_CC1NE_POS             2UL
#define TIM8_CCER_CC1NE_LEN             1UL
#define TIM8_CCER_CC1NP_POS             3UL
#define TIM8_CCER_CC1NP_LEN             1UL
#define TIM8_CCER_CC2E_POS              4UL
#define TIM8_CCER_CC2E_LEN              1UL
#define TIM8_CCER_CC2P_POS              5UL
#define TIM8_CCER_CC2P_LEN              1UL
#define TIM8_CCER_CC2NE_POS             6UL
#define TIM8_CCER_CC2NE_LEN             1UL
#define TIM8_CCER_CC2NP_POS             7UL
#define TIM8_CCER_CC2NP_LEN             1UL
#define TIM8_CCER_CC3E_POS              8UL
#define TIM8_CCER_CC3E_LEN              1UL
#define TIM8_CCER_CC3P_POS              9UL
#define TIM8_CCER_CC3P_LEN              1UL
#define TIM8_CCER_CC3NE_POS             10UL
#define TIM8_CCER_CC3NE_LEN             1UL
#define TIM8_CCER_CC3NP_POS             11UL
#define TIM8_CCER_CC3NP_LEN             1UL
#define TIM8_CCER_CC4E_POS              12UL
#define TIM8_CCER_CC4E_LEN              1UL
#define TIM8_CCER_CC4P_POS              13UL
#define TIM8_CCER_CC4P_LEN              1UL
#define TIM8_CCER_CC4NP_POS             15UL
#define TIM8_CCER_CC4NP_LEN             1UL
#define TIM8_CCER_CC5E_POS              16UL
#define TIM8_CCER_CC5E_LEN              1UL
#define TIM8_CCER_CC5P_POS              17UL
#define TIM8_CCER_CC5P_LEN              1UL
#define TIM8_CCER_CC6E_POS              20UL
#define TIM8_CCER_CC6E_LEN              1UL
#define TIM8_CCER_CC6P_POS              21UL
#define TIM8_CCER_CC6P_LEN              1UL

#define TIM8_CNT                        REGISTER(0x40013424UL)
#define TIM8_CNT_CNT_POS                0UL
#define TIM8_CNT_CNT_LEN                16UL
#define TIM8_CNT_UIFCP_POS              31UL
#define TIM8_CNT_UIFCP_LEN              1UL

#define TIM8_PSC                        REGISTER(0x40013428UL)
#define TIM8_PSC_PSC_POS                0UL
#define TIM8_PSC_PSC_LEN                16UL

#define TIM8_ARR                        REGISTER(0x4001342CUL)
#define TIM8_ARR_ARR_POS                0UL
#define TIM8_ARR_ARR_LEN                16UL

#define TIM8_RCR                        REGISTER(0x40013430UL)
#define TIM8_RCR_REP_POS                0UL
#define TIM8_RCR_REP_LEN                16UL

#define TIM8_CCR1                       REGISTER(0x40013434UL)
#define TIM8_CCR1_CCR1_POS              0UL
#define TIM8_CCR1_CCR1_LEN              16UL

#define TIM8_CCR2                       REGISTER(0x40013438UL)
#define TIM8_CCR2_CCR2_POS              0UL
#define TIM8_CCR2_CCR2_LEN              16UL

#define TIM8_CCR3                       REGISTER(0x4001343CUL)
#define TIM8_CCR3_CCR3_POS              0UL
#define TIM8_CCR3_CCR3_LEN              16UL

#define TIM8_CCR4                       REGISTER(0x40013440UL)
#define TIM8_CCR4_CCR4_POS              0UL
#define TIM8_CCR4_CCR4_LEN              16UL

#define TIM8_BDTR                       REGISTER(0x40013444UL)
#define TIM8_BDTR_DT_POS                0UL
#define TIM8_BDTR_DT_LEN                8U
#define TIM8_BDTR_LOCK_POS              8UL
#define TIM8_BDTR_LOCK_LEN              2U
#define TIM8_BDTR_OSSI_POS              10UL
#define TIM8_BDTR_OSSI_LEN              1U
#define TIM8_BDTR_OSSR_POS              11UL
#define TIM8_BDTR_OSSR_LEN              1U
#define TIM8_BDTR_BKE_POS               12UL
#define TIM8_BDTR_BKE_LEN               1U
#define TIM8_BDTR_BKP_POS               13UL
#define TIM8_BDTR_BKP_LEN               1U
#define TIM8_BDTR_AOE_POS               14UL
#define TIM8_BDTR_AOE_LEN               1U
#define TIM8_BDTR_MOE_POS               15UL
#define TIM8_BDTR_MOE_LEN               1U
#define TIM8_BDTR_BKF_POS               16UL
#define TIM8_BDTR_BKF_LEN               4U
#define TIM8_BDTR_BK2F_POS              20UL
#define TIM8_BDTR_BK2F_LEN              4U
#define TIM8_BDTR_BK2E_POS              24UL
#define TIM8_BDTR_BK2E_LEN              1U
#define TIM8_BDTR_BK2P_POS              25UL
#define TIM8_BDTR_BK2P_LEN              1U

#define TIM8_DCR                        REGISTER(0x40013448UL)
#define TIM8_DCR_DBA_POS                0UL
#define TIM8_DCR_DBA_LEN                5UL
#define TIM8_DCR_DBL_POS                8UL
#define TIM8_DCR_DBL_LEN                5UL

#define TIM8_DMAR                       REGISTER(0x4001344CUL)
#define TIM8_DMAR_DMAB_POS              0UL
#define TIM8_DMAR_DMAB_LEN              32UL

#define TIM8_OR1                        REGISTER(0x40013450UL)
#define TIM8_OR1_ETR_ADC1_RMP_POS       0UL
#define TIM8_OR1_ETR_ADC1_RMP_LEN       2UL
#define TIM8_OR1_ETR_ADC3_RMP_POS       2UL
#define TIM8_OR1_ETR_ADC3_RMP_LEN       2UL
#define TIM8_OR1_TI1_RMP_POS            4UL
#define TIM8_OR1_TI1_RMP_LEN            1UL

#define TIM8_CCMR3                      REGISTER(0x40013454UL)
#define TIM8_CCMR3_OC5FE_POS            2UL
#define TIM8_CCMR3_OC5FE_LEN            1UL
#define TIM8_CCMR3_OC5PE_POS            3UL
#define TIM8_CCMR3_OC5PE_LEN            1UL
#define TIM8_CCMR3_OC5M_POS             4UL
#define TIM8_CCMR3_OC5M_LEN             3UL
#define TIM8_CCMR3_OC5CE_POS            7UL
#define TIM8_CCMR3_OC5CE_LEN            1UL
#define TIM8_CCMR3_OC6FE_POS            10UL
#define TIM8_CCMR3_OC6FE_LEN            1UL
#define TIM8_CCMR3_OC6PE_POS            11UL
#define TIM8_CCMR3_OC6PE_LEN            1UL
#define TIM8_CCMR3_OC6M_POS             12UL
#define TIM8_CCMR3_OC6M_LEN             3UL
#define TIM8_CCMR3_OC6CE_POS            15UL
#define TIM8_CCMR3_OC6CE_LEN            1UL
#define TIM8_CCMR3_OC5M3_POS            16UL
#define TIM8_CCMR3_OC5M3_LEN            1UL
#define TIM8_CCMR3_OC6M3_POS            24UL
#define TIM8_CCMR3_OC6M3_LEN            1UL

#define TIM8_CCR5                       REGISTER(0x40013458UL)
#define TIM8_CCR5_CCR5_POS              0UL
#define TIM8_CCR5_CCR5_LEN              16UL
#define TIM8_CCR5_GC5C1_POS             29UL
#define TIM8_CCR5_GC5C1_LEN             1UL
#define TIM8_CCR5_GC5C2_POS             30UL
#define TIM8_CCR5_GC5C2_LEN             1UL
#define TIM8_CCR5_GC5C3_POS             31UL
#define TIM8_CCR5_GC5C3_LEN             1UL

#define TIM8_CCR6                       REGISTER(0x4001345CUL)
#define TIM8_CCR6_CCR6_POS              0UL
#define TIM8_CCR6_CCR6_LEN              16UL

#define TIM8_OR2                        REGISTER(0x40013460UL)
#define TIM8_OR2_BKINE_POS              0UL
#define TIM8_OR2_BKINE_LEN              1UL
#define TIM8_OR2_BKCMP1E_POS            1UL
#define TIM8_OR2_BKCMP1E_LEN            1UL
#define TIM8_OR2_BKCMP2E_POS            2UL
#define TIM8_OR2_BKCMP2E_LEN            1UL
#define TIM8_OR2_BKDF1BK2E_POS          8UL
#define TIM8_OR2_BKDF1BK2E_LEN          1UL
#define TIM8_OR2_BKINP_POS              9UL
#define TIM8_OR2_BKINP_LEN              1UL
#define TIM8_OR2_BKCMP1P_POS            10UL
#define TIM8_OR2_BKCMP1P_LEN            1UL
#define TIM8_OR2_BKCMP2P_POS            11UL
#define TIM8_OR2_BKCMP2P_LEN            1UL
#define TIM8_OR2_ETRSEL_POS             14UL
#define TIM8_OR2_ETRSEL_POS             3U

#define TIM8_OR3                        REGISTER(0x40013464UL)
#define TIM8_OR3_BK2INE_POS             0UL
#define TIM8_OR3_BK2INE_LEN             1UL
#define TIM8_OR3_BK2CMP1E_POS           1UL
#define TIM8_OR3_BK2CMP1E_LEN           1UL
#define TIM8_OR3_BK2CMP2E_POS           2UL
#define TIM8_OR3_BK2CMP2E_LEN           1UL
#define TIM8_OR3_BK2DF1BK3E_POS         8UL
#define TIM8_OR3_BK2DF1BK3E_LEN         1UL
#define TIM8_OR3_BK2INP_POS             9UL
#define TIM8_OR3_BK2INP_LEN             1UL
#define TIM8_OR3_BK2CMP1P_POS           10UL
#define TIM8_OR3_BK2CMP1P_LEN           1UL
#define TIM8_OR3_BK2CMP2P_POS           11UL
#define TIM8_OR3_BK2CMP2P_LEN           1UL

#endif /* #ifndef _REG_TIM8_H_ */
